config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :hostings do
  	resources :comments, except: [:index, :show]
  	collection do
  		get 'search'
  	end
  end
  
  root 'hostings#index'

  match '/how_it_works', to: 'pages#how_it_works', via: :get
  match '/about_us', 	 to: 'pages#about_us', 	   via: :get

end

app/models/ability2.rb
#class Ability
 # include CanCan::Ability

  #def initialize(user)

  #	if user.admin?

  #		can :update, Hosting do |hosting| 
  #			hosting.user == user
  #		end

  #		can :destroy, Hosting do |hosting| 
  #			hosting.user == user
  #		end

  #		can :destroy, Comment do |comment| 
  #			comment.user == user
  #		end

  #	else

  #		can :create, Hosting
  #		can :create, Comment

  #end
#end
#end

app/models/category.rb
class Category < ActiveRecord::Base

    has_many :hostings

end

app/models/comment.rb
class Comment < ActiveRecord::Base


    belongs_to :hosting
    belongs_to :user

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/hosting.rb
class Hosting < ActiveRecord::Base
    
    has_many :comments
    belongs_to :category
    validates_presence_of :name
    validates_presence_of :description
    validates_presence_of :country
    validates_presence_of :city
    validates_presence_of :email

    geocoded_by :full_address
    after_validation :geocode

    mount_uploader :image, ImageUploader

    def full_address
    	[address1, address2, country, city, county, postalcode].join (',')
    end

    def self.search(params)
    	hostings = Hosting.where(category_id: params[:category].to_i)
    	hostings = hostings.where("country like ? or city like ?", "%#{params[:search]}%", "%#{params[:search]}") if params[:search].present?
    	hostings = hostings.near(params[:location], 200) if params[:location].present?
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # acts_as_messageable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 # before_action :add_parameters_to_user, if: :devise_controller?

  def add_parameters_to_user

 #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :country])
 #   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :country])
end
end

app/controllers/categories_controller.rb
class Categories < ApplicationController

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_hosting
	before_action :authenticate_user!

	def new
		@comment = Comment.new(comment: @hosting)
	end

	def create
		@comment = current_user.comments.build(comment_params)
		@comment.hosting = @hosting
		@comment.save
		redirect_to @hosting
	end

	private

	def set_hosting
		@hosting = Hosting.find(params[:hosting_id])
	end

	def comment_params
		params.require(:comment).permit(:comment, :rating)
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
	end

	def show
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to @event
		else
			render 'new'
		end
	end

	def edit

	end

	def update
	end

	def destroy
	end

	private

	def event_params
	params.require(:event).permit  :name, :date, :address1, :address2, :description, :country, :city, :postalcode, :email
      t.string :socialmedia
      t.category :integer
      t.latitude :float
      t.longitude :float
      t.image :string 
	end

	def find_event
	end

end

app/controllers/hostings_controller.rb
class HostingsController < ApplicationController

    before_action :authenticate_user!, only: [:create, :new]
    before_action :is_admin?, only: [:edit, :update, :destroy]

    def index

     #     @hostings = Hosting.all
      #  if params[:search]
       #     @hostings = Hosting.search(params[:search]).order("created_at DESC")
       # else
        #    @hosting = Hosting.all.order('created_at DESC')
    #end


        #visitor_latitude = request.location.latitude
        #visitor_longitude = request.location.longitude

        #developer latitude and longitude
        visitor_latitude = 53.3811
        visitor_longitude = -1.4701

        @hostings = Hosting.near([visitor_latitude, visitor_longitude], 400)
        @hostings = Hosting.all.near([visitor_latitude, visitor_longitude], 400)
    end

    def new
    	@hosting = Hosting.new
    end

    def create
    	@hosting = Hosting.new(hosting_params)
    	if @hosting.save
    	redirect_to @hosting
        else
            flash[:danger] = @hosting.errors.full_messages.to_sentence
            render 'new'
        end
    end
    
    def show
        @hosting = Hosting.find(params[:id])
        @comments =Comment.where(hosting_id: @hosting)
    end

    def search
        if params[:category].blank?
        @hostings = Hosting.all
        else
       @hostings = Hosting.search(params)
       end
    end

    def edit
        @hosting =Hosting.find(params[:id])

        unless current_user == @hosting.user
        redirect_to(@hosting, notice: "You cannot edit this host") and return
        end
    end

    def update
        @hosting = Hosting.find(params[:id])
        @hosting.update(hosting_params)
        redirect_to @hosting
    end

    def destroy
        @hosting = Hosting.find(params[:id])
        @hosting.destroy
        redirect_to root_path
    end

    private 
    	def hosting_params
    		params.require(:hosting).permit(:name, :description, :address1, :address2, :category_id,
    										:country, :city, :county, :postalcode, :phone, :email, :image ,:socialmedia )
    	end

        def is_admin?
          if !current_user.try(:admin?)
                flash[:danger] = "You are not authorized to edit or delete."
                redirect_to root_path
            end
        end
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController

	def how_it_works
	end

	def about_us
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/comments/new.html.erb
<%= form_for [@hosting, @comment] do |f| %>
	<%= f.text_area :comment %> </br>
	<%= f.submit %>
<% end %>

app/views/events/show.html.erb

    <div class="container page-content">
      <div class="row">
        <div class="span8">
          <div class="box-container">
          
              <%= image_tag @hosting.image_url %>

            </div><!-- .cycle-slideshow -->
            <div id="adv-custom-pager"></div>
            <div class="clearfix">
              <div class="clearfix padding30">
                <h2 class="prop-title pull-left margin0"><%= @hosting.name %>
                  
                   <% if current_user.try(:admin?) %>  
                <small><%= link_to "Edit", edit_hosting_path, class: "btn btn-primary btn-mini" %></small>
                <small><%= link_to "Delete", hosting_path, method: :delete, data: {confirm: "Are you sure you want to delete?"}, class: "btn btn-danger btn-mini" %></small>
                <% else %>
                <% end %>              


                <!-- if hosting.user == current_user -->

                </h2>
                <span class="prop-price pull-right serif italic">*****</span>
              </div>
              <div class="clearfix padding030 row-fluid">
                <ul class="more-info pull-left span6">
                   <li class="info-label clearfix"><span class="pull-left">Category</span>
                    <span class="qty pull-right"><%= @hosting.category.name %></span></li> 
                     <li class="info-label clearfix"><span class="pull-left">Email</span>
                    <span class="qty pull-right"><%= @hosting.email %></span></li>
                  <li class="info-label clearfix"><span class="pull-left">Social media</span>
                    <span class="qty pull-right"></span><%= @hosting.socialmedia %></li>
                  <li class="info-label clearfix"><span class="pull-left">Phone</span>
                    <span class="qty pull-right"><%= @hosting.phone %></span></li>
                </ul>
                <ul class="more-info pull-right span6">
                  <li class="info-label clearfix"><span class="pull-left">location:</span>
                    <span class="qty pull-right">

                     <!-- <%= @hosting.address1 %>, -->
                     <!-- <%= @hosting.address2 %>, -->
                      <%= @hosting.country  %>, 
                      <%= @hosting.city     %>, 
                    <!-- <%= @hosting.county   %> -->
                    <!-- <%= @hosting.postalcode %>. -->

                    </span></li>
                <!--  <li class="info-label clearfix"><span class="pull-left">Listing
                    type:</span>
                    <span class="qty pull-right"></span></li>
                  <li class="info-label clearfix"><span class="pull-left">...</span>
                    <span class="qty pull-right">...</span></li>
                  <li class="info-label clearfix"><span class="pull-left">...</span>
                    <span class="qty pull-right">...</span></li> -->
                </ul>
              </div>
              <div class="clearfix padding30">
                <h3>About Me</h3>
                <p> <%= @hosting.description %> </p>
              </div>
                 <div class="clearfix padding30">
                  <%= link_to "write a comment", new_hosting_comment_path(@hosting), class: "btn btn-small btn-realto" %>
                <h3>Comments</h3>
                  <% if @comments.blank? %>
                   <p>No comments yet</p>
                  <% else %>
                      <table class='table'>
                        <thead>
                          <tr>
                            <th class="col-mid-3"></th>
                            <th class="col-mid-9"></th>
                          </tr>
                          <tbody> 
                      <% @comments.each do |comment| %>
                  <tr>
                    <td>
                      <h5> <%= "#{comment.user.first_name} #{comment.user.last_name} #{comment.user.country}" %></h5>
                    </td>
                  <td>
                  <%= comment.comment %>
                </td>
                </tr>
                  <% end %>
                 </tbody>
                </table> 
              <% end %>
              </div>
            </div>
          </div>
        </div>
        <!-- .span8 -->

            
          <!-- .agent-box -->
          
          <!-- .search-form -->
        </div>
        <!-- .span4 -->
      </div>
      <!-- .row -->
    </div>
    <!-- .container -->
          <!-- .adv-message  -->
        </div>
      </div>
    </div>
     
  

app/views/hostings/index.html.erb

<!-- begin header -->
<div id="home-search-container">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="widget pull-right">
          <div class="row">
            <div class="span12 head-container">
              <div class="row">
                <div class="span8 hidden-phone">
                  <h2 class="head-title"><mark>Welcome to Hospitality </mark> </h2>
                   <p class="head-message"><strong> <mark>A new international movement to share hospitality. </mark></strong><br />
                 </mark><mark>Welcome likeminded people into your world. Join now. </mark></p>
                  <%= link_to "list yourself now!" , new_hosting_path,class: "btn btn-large btn-realto head-message" %> 
                  <!-- <p><%= link_to "List your event now!" , new_event_path,class: "btn btn-large btn-realto span3 header-cta" %> </p> -->
                
                      </div>
                <div class="span3">
                  <div class="search-form">
        
        
   <!-- <body>
    <video id="bgVideo" autoplay loop poster="image.png">
      <!-- Video is embedded in the WEBM format -->
    <!--<source src="video.webm" type="video/webm">
    </video>
  </body> --> 
   
                    <p> Search hospitable people by Country. </p>
                    
                    <%= form_tag search_hostings_path, method: :get do |f| %>
                    <!-- <%= text_field_tag :search, nil, placeholder: "Interests " %> -->
                    <%= text_field_tag  :location, nil, placeholder: "Denmark, England etc." %>
                    <!--<%= select_tag :category, options_for_select(Category.all.map{ |c| [c.name, c.id]}) %>--!>
                    <%= submit_tag 'Search' %>
                    <% end %>
                  
                
                  </div>
                  <!-- .search-form -->   
                </div>
                <!-- .span4 -->
              </div>
            </div>        
          </div>
          <!-- .row -->
        </div>
        <!-- .search-holder -->
      </div>
      <!-- .span12 -->
    </div>
    <!-- .row -->
  </div>
  <!-- .container -->
</div>
<div id="latest-properties">
  <div class="container">
    <div class="row">
      <p><%= link_to "View all hosts" ,search_hostings_path,class: "pull-right btn btn-realto span3" %> </p>
      <div class="span12">
        <h2 class="secion-title"><mark>Hospitable people near you: </mark></h2>
      <div class="carousel-navigation pull-right">
          <a class="left carousel-control pull-left" href="#realto-carousel" data-slide="prev">‹</a>
          <a class="right carousel-control pull-right" href="#realto-carousel" data-slide="next">›</a>
        </div>
      </div>
    </div>
    
    <!-- Begin Carousel -->
    <div class="row">
      <div id="realto-carousel" class="carousel slide span12">
        
        <div class="carousel-inner">
          <div class="item active">
            <ul class="thumbnails">
              <% @hostings.last(3).each do |hosting| %>
              
              <li class="span4 box-container">
                <div class="holder">
                  <a class="overlay" title="property title" href="#">
                    <span class="more"></span>
                  
                     <% if hosting.image_url.present? %>
                                    <%= link_to image_tag(hosting.image.url.to_s), hosting %>
                                    <% else %>
                                    <%= link_to image_tag("http://placehold.it/370x210"), hosting %>
                                    <% end %>
                  </a>
                  <span class="prop-tag"><%= hosting.city %></span>
                  <div class="prop-info">
                    <h3 class="prop-title"><%= link_to hosting.name, hosting %></h3>
                    <ul class="more-info clearfix">
                      <li class="info-label clearfix"><span class="pull-left">Location</span> <span class="qty pull-right"><%= hosting.city %></span></li>
                     <li class="info-label clearfix"><span class="pull-left">Category</span> <span class="qty pull-right"><%= hosting.category.name %></span></li> 
                    </ul>
                  </div>
                </div>

                <% end %>
              <!-- .item -->
              
             </div class="item">
              <ul class="thumbnails">
                <% @hostings.order(:id).reverse_order.limit(3).offset(3).each do |hosting| %>

              <li class="span4 box-container">
                <div class="holder">
                  <a class="overlay" title="property title" href="#">
                    <span class="more"></span>
                     <% if hosting.image_url.present? %>
                                    <%= link_to image_tag(hosting.image.url.to_s), hosting %>
                                    <% else %>
                                        <%= link_to image_tag("http://placehold.it/370x210"), hosting %>
                                    <% end %>
                  </a>
                  <span class="prop-tag">Same country!</span>
                  <div class="prop-info">
                    <h3 class="prop-title"><%= link_to hosting.name, hosting %></h3>
                    <ul class="more-info clearfix">
                      <li class="info-label clearfix"><span class="pull-left">Location</span> <span class="qty pull-right"><%= hosting.city %></span></li>
                     <li class="info-label clearfix"><span class="pull-left">Category</span> <span class="qty pull-right"><%= hosting.category.name %></span></li> 
                    </ul>
                  </div>
                </div>

                <% end %>
        </ul>
      </div><!-- .carousel-inner -->
      </div>
    </div><!--End Carousel-->
    
  </div><!-- .container  -->
</div><!-- #latest-properties  -->


<!-- #latest-properties  -->
<!--<div class="container">
  <div class="row">
    <div class="home-bottom-top">
      <div class="span4">
        <div class="info-box">
          <h2 class="secion-title">Why choose us?</h2>
          <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
            magna aliqua adipisicing elit seddo eiusmod tempor.</p>
          <p>Sed perspiciatis unde omnisiste natus error voluptatem remopa
            accusantium doloremque laudantium, totam rem aperiam.</p>
          <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
        </div>
      </div> -->
      <!-- .span4 -->
      <!--<div class="span4">
        <div class="info-box">
          <h3 class="info-head">Designed for your business</h3>
          <div class="row clearfix">
            <div class="pull-left icons hidden-phone">
              <i class="icon-briefcase"></i>
            </div>
            <div class="span3">
              <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                magna aliqua adipisicing elit seddo eiusmod tempor.</p>
              <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
            </div>
          </div> -->
          <!-- .clearfix -->
        </div>
        <!-- .info-box -->
        <!--
        <div class="info-box">
          <h3 class="info-head">Ample Customizations</h3>
          <div class="row clearfix">
            <div class="pull-left icons hidden-phone">
              <i class="icon-cogs"></i>
            </div>
            <div class="span3">
              <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                magna aliqua adipisicing elit seddo eiusmod tempor.</p>
              <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
            </div>
          </div> -->
          <!-- .clearfix -->
        </div>
        <!-- .info-box -->
      </div>
      <!-- .span4 -->
      <!--
      <div class="span4">
        <div class="info-box">
          <h3 class="info-head">Fully Responsive</h3>
          <div class="row clearfix">
            <div class="pull-left icons hidden-phone">
              <i class="icon-move"></i>
            </div>
            <div class="span3">
              <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                magna aliqua adipisicing elit seddo eiusmod tempor.</p>
              <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
            </div>
          </div> -->
          <!-- .clearfix -->
        </div>
        <!-- .info-box -->
        <!--
        <div class="info-box">
          <h3 class="info-head">Bootstrap Compatible</h3>
          <div class="row clearfix">
            <div class="pull-left icons hidden-phone">
              <i class="icon-thumbs-up"></i>
            </div>
            <div class="span3">
              <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                magna aliqua adipisicing elit seddo eiusmod tempor.</p>
              <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
            </div>
          </div> -->
          <!-- .clearfix -->
        </div>
        <!-- .info-box -->
      </div>
      <!-- .span4 -->
    </div>
  </div>
</div>

<!--<div class="container">
  <div class="row">
    <div class="span8">
      <h2 class="secion-title">Meet our agents</h2>
      <div class="row">
        <div class="span2">
          <div class="home-agents widget">
            <a class="overlay" href="#" title="agent name">
              <span class="more"></span>
              <img alt="image" class="media-object" src="images/agent-01.jpg" />
            </a>
            <p class="home-agent-name">John Doe</p>
            <a class="serif italic" href="#" title="View profile page">View profile
              page &raquo;</a>
          </div> -->
          <!-- .home-agents -->
        <!--
        </div>
        <div class="span2">
          <div class="home-agents widget">
            <a class="overlay" href="#" title="agent name">
              <span class="more"></span>
              <img alt="image" class="media-object" src="images/agent-02.jpg" />
            </a>
            <p class="home-agent-name">Susan Underwood</p>
            <a class="serif italic" href="#" title="View profile page">View profile
              page &raquo;</a>
          </div> -->
          <!-- .home-agents -->
        
      <!--
        </div>
        <div class="span2">
          <div class="home-agents widget">
            <a class="overlay" href="#" title="agent name">
              <span class="more"></span>
              <img alt="image" class="media-object" src="images/agent-06.jpg" />
            </a>
            <p class="home-agent-name">Erik Peterson</p>
            <a class="serif italic" href="#" title="View profile page">View profile
              page &raquo;</a>
          </div> 
        -->
          <!-- .home-agents -->
        </div>
        <!--
        <div class="span2">
          <div class="home-agents widget">
            <a class="overlay" href="#" title="agent name">
              <span class="more"></span>
              <img alt="image" class="media-object" src="images/agent-07.jpg" />
            </a>
            <p class="home-agent-name">Lu Jackson</p>
            <a class="serif italic" href="#" title="View profile page">View profile
              page &raquo;</a>
          </div>
        -->
          <!-- .home-agents -->
        </div>
      </div>
    </div>
    <!-- .span8  -->
    <!--
    <div class="span4">
      <div class="home-blog-articles widget">
        <h2 class="secion-title">Articles from the Blog</h2>
        <ul>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Lorem ipsum dolor sit amet, consectetur
              adipiscing</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Duis suscipit venenatis pellentesque tempor
              libero</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Etiam aliquet aliquam metus in tristique</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Cras venenatis pellentesque venenatis
              pellentesque</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Vivamus vitae venenatis pellentesque nunc sed
              nisl</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">In tempus venenatis pellentesquetempor</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Suspendisse vulputate venenatis pellentesque
              quis</a></li>
        </ul> -->
      </div>
    </div>
    <!-- .span4  -->
  </div>
</div>
 
   <div class="container">
  <div class="row">
    <div class="span4 box-container">
      <div class="row adv-message clearfix">
        <div class="pull-left span7">
          <p class="secion-title bold">Still looking?.</p>
          <p class="lower-line">.</p>
        </div>
        <!-- .pull-left -->

        <p><%= link_to "View all hosts" ,search_hostings_path,class: "pull-right btn btn-realto span3" %> </p>

      </div>
      <!-- .adv-message  -->
    </div>
  </div>
</div>    

app/views/hostings/show.html.erb

    <div class="container page-content">
     <%= image_tag @hosting.image_url %>
      <div class="row">
        <div class="span8">
          <div class="box-container">
          
            <!-- .cycle-slideshow -->
            <div id="adv-custom-pager"></div>
            <div class="clearfix">
              <div class="clearfix padding10">
                <h2 class="prop-title pull-left margin10"><%= @hosting.name %>
                </h2>
                
                <% if current_user.try(:admin?) %>
                <h2 class="prop-title pull-right margin10">
                <small><%= link_to "Edit", edit_hosting_path, class: "btn btn-primary btn-mini" %></small>
                <small><%= link_to "Delete", hosting_path, method: :delete, data: {confirm: "Are you sure you want to delete?"}, class: "btn btn-danger btn-mini" %></small>
                </h2>
                <% else %>
                <% end %>
                
                
                <span class="prop-price pull-left serif italic">*</span>
              </div>
              <div class="clearfix padding10 row-fluid">
                <ul class="more-info pull-left span6">
                  <li class="info-label2 clearfix"><span class="pull-left">Category</span>
                  <span class="qty pull-right"><%= @hosting.category.name %></span></li> 
                     <li class="info-label2 clearfix"><span class="pull-left">Email</span>
                    <span class="qty pull-right"><%= @hosting.email %></span></li>
                  <li class="info-label2 clearfix"><span class="pull-left">Portfolio</span>
                    <span class="qty pull-right"></span><%= @hosting.socialmedia %></li>
                  <li class="info-label2 clearfix"><span class="pull-left">Phone</span>
                    <span class="qty pull-right"><%= @hosting.phone %></span></li>
                </ul>
                <ul class="more-info2 pull-right2 span6">
                  <li class="info-label clearfix"><span class="pull-left">location:</span>
                    <!--<span class="qty pull-right">-->
                      <%= @hosting.country  %>, 
                      <%= @hosting.city     %>, 
                     <!-- <%= @hosting.address1 %>, -->
                     <!-- <%= @hosting.address2 %>, -->
                    <!-- <%= @hosting.county   %> -->
                    <!-- <%= @hosting.postalcode %>. -->

                    <!--</span>--></li>
                <!--  <li class="info-label clearfix"><span class="pull-left">Listing
                    type:</span>
                    <span class="qty pull-right"></span></li>
                  <li class="info-label clearfix"><span class="pull-left">...</span>
                    <span class="qty pull-right">...</span></li>
                  <li class="info-label clearfix"><span class="pull-left">...</span>
                    <span class="qty pull-right">...</span></li> -->
                </ul>
              </div>
              <div class="clearfix padding30">
                <h3>About Me</h3>
                <p> <%= @hosting.description %> </p>
              </div>
                 <div class="clearfix padding30">
                <h3>Comments</h3>
                  <% if @comments.blank? %>
                   <p>No comments yet</p>
                  <% else %>
                      <table class='table'>
                        <thead>
                          <tr>
                            <th class="col-mid-3"></th>
                            <th class="col-mid-9"></th>
                          </tr>
                          <tbody> 
                      <% @comments.each do |comment| %>
                  <tr>
                  
                    <td>
                      <h5> <%= "#{comment.user.first_name} #{comment.user.last_name} #{comment.user.country}" %></h5>
                    </td>
                  <td>
                  <%= comment.comment %>
                </td>
                </tr>
                  <% end %>
                 </tbody>
                </table> 
              <% end %>
              </mark>
              <%= link_to "write a comment", new_hosting_comment_path(@hosting), class: "btn btn-small btn-realto" %>
              </div>
            </div>
          </div>
        </div>
        <!-- .span8 -->

            
          <!-- .agent-box -->
          
          <!-- .search-form -->
        </div>
        <!-- .span4 -->
      </div>
      <!-- .row -->
    </div>
    <!-- .container -->
          <!-- .adv-message  -->
        </div>
      </div>
    </div>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospitality</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %> 
<div class='container'>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>
</div>

<%= yield %>
<%= render 'layouts/footer' %> 
</body>
</html>